### ISSUE TITLE
Adding Images From Remote Source

### ISSUE THREAD

**Issue by chrisamerson21** [tinovyatkin/pass-js#444]
I try to add a pass image or template image from a S3 bucket, but I get an error that there's no such file or directory. I think this will only allow for images in the file system. Is there a way to add them from a remote url? If so, I can't find it in the docs. I have to build the template manually, so storing the template in S3 won't work.

**Comment by FreshApps** [comment]
My solution was to download the image from url and add the image as Buffer to pass.images

**Comment by tinovyatkin** [comment]
It allows you to add images as Buffers, so, download them into a Buffer first.
